name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK with release key
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > release.keystore
          jarsigner -verbose \
            -keystore release.keystore \
            -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}" \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            "${{ secrets.RELEASE_KEY_ALIAS }}"
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-signed.apk

      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | head -1 | awk '{ print $2 }' | tr -d '"')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version_name }}.${{ github.run_number }}
          release_name: Release v${{ steps.get_version.outputs.version_name }}.${{ github.run_number }}
          files: app/build/outputs/apk/release/app-release-signed.apk
          draft: false
          prerelease: false
